server:
  port: 50211
spring:
  datasource:
    url: jdbc:mysql://dev.tanxin.info:3306/tanxin-db?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: tanxin
    password: asEedio234#r3
  redis:
    host: dev.tanxin.info
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: Lafengyun5566
    database: 9
    #连接超时时间（毫秒）
    timeout: 30000
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0